"""Add category to Product

Revision ID: 040a4dcdf222
Revises: c23319b770e5
Create Date: 2025-06-11 18:12:49.061878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040a4dcdf222'
down_revision = 'c23319b770e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
