"""Remove username from User model

Revision ID: 62ae614db141
Revises: c4d24d8d2200
Create Date: 2025-06-12 23:33:28.263627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62ae614db141'
down_revision = 'c4d24d8d2200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('username'))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=80), nullable=False))
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)

    # ### end Alembic commands ###
