name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'titan-alchemy-forgefront/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'titan-alchemy-forgefront/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build and run tests
      working-directory: ./titan-alchemy-forgefront
      run: |
        docker build --target test -t frontend-test .
        docker run --name frontend-test frontend-test
    
    - name: Copy coverage from container
      working-directory: ./titan-alchemy-forgefront
      run: |
        docker cp frontend-test:/app/coverage .
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./titan-alchemy-forgefront/coverage

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push Docker image
      working-directory: ./titan-alchemy-forgefront
      run: |
        docker build --target production -t ${{ secrets.ACR_LOGIN_SERVER }}/titan-alchemy-frontend:${{ github.sha }} .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/titan-alchemy-frontend:${{ github.sha }}
        docker tag ${{ secrets.ACR_LOGIN_SERVER }}/titan-alchemy-frontend:${{ github.sha }} ${{ secrets.ACR_LOGIN_SERVER }}/titan-alchemy-frontend:latest
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/titan-alchemy-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'titan-alchemy-frontend'
        images: ${{ secrets.ACR_LOGIN_SERVER }}/titan-alchemy-frontend:${{ github.sha }} 